[project]
name = "sound-mastering"
version = "0.1.0"
description = "Audio mastering scripts for Suno AI tracks"
authors = [
    {name = "SoundMastering"}
]
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "numpy (>=2.4.4,<3.0.0)",
    "librosa (>=0.11.0,<0.12.0)",
    "soundfile (>=0.13.1,<0.14.0)",
    "scipy (>=1.17.1,<2.0.0)",
    "pyloudnorm (>=0.2.0,<0.3.0)",
    "tqdm (>=4.67.3,<5.0.0)",
    "rich (>=14.3.3,<15.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "pytaglib (>=3.2.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
